name: panzerkraft_demo
//1.- Descripción concisa orientada a la demo solicitada.
description: Demo de Flutter lista para Android con una pantalla de muestra.
publish_to: "none"
version: 0.1.0+1

environment:
  //2.- Define la versión mínima del SDK de Dart/Flutter compatible con la plantilla.
  sdk: "^3.9.2"

dependencies:
  flutter:
    sdk: flutter
  //3.- Incluye íconos de Cupertino para paridad visual en iOS y Android.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  //4.- Mantiene reglas de lint recomendadas para código limpio en la demo.
  flutter_lints: ^5.0.0

flutter:
  //5.- Activa el conjunto de íconos de Material para los widgets usados en la demo.
  uses-material-design: true
