name: ubberapp
description: Client prototype for reporting and consulting incidents against the Ubberapp backend.
publish_to: "none"
version: 0.1.0+1

environment:
  # //1.- Ajustamos el SDK mínimo a la versión compatible con el proyecto de referencia.
  sdk: "^3.9.2"

dependencies:
  flutter:
    sdk: flutter
  # //2.- Sincroniza las dependencias base con la aplicación de referencia para asegurar compatibilidad.
  cupertino_icons: ^1.0.8
  # //3.- Agrega Riverpod para la gestión de estado igual que en la app ciudadana.
  flutter_riverpod: ^2.5.1
  # //4.- Añade Dio para peticiones HTTP avanzadas utilizadas por la app de referencia.
  dio: ^5.7.0
  # //5.- Incluye Equatable para simplificar comparaciones de modelos.
  equatable: ^2.0.5
  # //6.- go_router centraliza la navegación declarativa y permitirá el nuevo flujo de pantallas.
  go_router: ^13.2.0
  google_maps_flutter: ^2.7.0
  geolocator: ^13.0.1
  http: ^1.2.2
  device_info_plus: ^10.1.0
  flutter_secure_storage: ^9.2.2
  uuid: ^4.5.1
  # //6.- Habilita el sistema de diseño shadcn para alinear tarjetas y botones personalizados.
  shadcn_flutter: ^0.0.44
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.0
  # //7.- Activa las reglas de lint recomendadas para Flutter.
  flutter_lints: ^5.0.0
  # //8.- Integra flutter_launcher_icons para generar los íconos nativos desde el recurso proporcionado.
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/
    # //9.- assets/icons contendrá los placeholders de íconos suministrados externamente.
    - assets/icons/
    # //10.- internal/assets alberga los íconos personalizados enviados por el backend ciudadano.
    - internal/assets/

# //11.- Configuramos flutter_launcher_icons para reutilizar el recurso proporcionado sin versionar íconos generados.
flutter_launcher_icons:
  # //12.- Habilitamos la generación automática de íconos Android.
  android: true
  # //13.- Habilitamos la generación automática de íconos iOS.
  ios: true
  # //14.- Referenciamos el ícono entregado en android/assets/icon/app_icon.png sin crear artefactos sustitutos.
  image_path: "android/assets/icon/app_icon.png"
