name: app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  # //1.- Alinea la versión del SDK de Dart con la configuración traída desde xolotl para asegurar compatibilidad.
  sdk: "^3.9.2"

dependencies:
  flutter:
    sdk: flutter
  # //2.- Mantiene los íconos de Cupertino sincronizados con la referencia.
  cupertino_icons: ^1.0.8
  # //3.- Incorpora Riverpod igual que en xolotl para habilitar patrones avanzados de estado.
  flutter_riverpod: ^2.5.1
  # //4.- Añade Dio para peticiones HTTP consistentes con la app de referencia.
  dio: ^5.7.0
  # //5.- Usa Equatable para comparaciones de modelos alineadas con el flujo ciudadano.
  equatable: ^2.0.5
  # //6.- Actualiza Google Maps para reflejar el mismo nivel de SDK que xolotl.
  google_maps_flutter: ^2.7.0
  # //7.- Ajusta Geolocator a la versión empleada por xolotl para permisos recientes.
  geolocator: ^13.0.1
  # //8.- Incluye http como soporte ligero para consultas directas.
  http: ^1.2.2
  # //9.- Device info replica la recopilación de diagnóstico de la referencia.
  device_info_plus: ^10.1.0
  # //10.- Flutter secure storage mantiene la capa cifrada utilizada por xolotl.
  flutter_secure_storage: ^9.2.2
  # //11.- UUID proporciona identificadores compatibles con la lógica ciudadana.
  uuid: ^4.5.1
  # //12.- shadcn_flutter habilita los componentes de diseño compartidos.
  shadcn_flutter: ^0.0.44
  # //13.- Conserva Provider para no romper la lógica existente de Panzerkraft.
  provider: ^6.0.5
  # //14.- Mantiene intl para las utilidades de formato actuales.
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # //15.- Expone el paquete test igual que en la referencia para utilidades de consola.
  test: ^1.24.0
  # //16.- Conserva la interfaz de Geolocator usada en pruebas locales.
  geolocator_platform_interface: ^4.1.1
  # //17.- Actualiza flutter_lints al nivel 5.0.0 indicado por la configuración objetivo.
  flutter_lints: ^5.0.0

flutter:
  # //18.- Mantiene los íconos de Material disponibles según la guía de xolotl.
  uses-material-design: true
  assets:
    # //19.- Declara la carpeta general de assets replicando la estructura de referencia.
    - assets/
    # //20.- Añade los íconos externos utilizados por la app hermana.
    - assets/icons/
    # //21.- Expone los assets internos compartidos con el backend ciudadano.
    - internal/assets/
